# Generated by Django 4.0.5 on 2022-10-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INTERFACE', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='analysisararview',
            table='analysis_ar_ar_view',
        ),
        migrations.AlterModelTable(
            name='analysisfissiontracksview',
            table='analysis_fission_tracks_view',
        ),
        migrations.AlterModelTable(
            name='analysisuheview',
            table='analysis_u_he_view',
        ),
        migrations.AlterModelTable(
            name='contactsview',
            table='contacts_view',
        ),
        migrations.AlterModelTable(
            name='fieldmissionsview',
            table='field_missions_view',
        ),
        migrations.AlterModelTable(
            name='formationsview',
            table='formations_view',
        ),
        migrations.AlterModelTable(
            name='lithologydescriptionview',
            table='lithology_description_view',
        ),
        migrations.AlterModelTable(
            name='locationsview',
            table='locations_view',
        ),
        migrations.AlterModelTable(
            name='measurementslinesview',
            table='measurements_lines_view',
        ),
        migrations.AlterModelTable(
            name='measurementsplanesview',
            table='measurements_planes_view',
        ),
        migrations.AlterModelTable(
            name='missionsview',
            table='missions_view',
        ),
        migrations.AlterModelTable(
            name='samplesectionsview',
            table='sample_sections_view',
        ),
        migrations.AlterModelTable(
            name='samplesview',
            table='samples_view',
        ),
    ]
