# Generated by Django 4.0.5 on 2022-10-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INTERFACE', '0002_alter_analysisararview_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldMissionsView',
        ),
    ]
