# Generated by Django 4.0.5 on 2022-10-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INTERFACE', '0004_fieldmissionsview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldMissionsView',
        ),
    ]
