# Generated by Django 4.0.5 on 2022-10-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTERFACE', '0005_delete_fieldmissionsview'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMissionsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.TextField(blank=True, db_column='Mission Name', null=True)),
                ('regional_place', models.TextField(blank=True, db_column='Regional place', null=True)),
                ('start_date', models.DateField(blank=True, db_column='Start date', null=True)),
                ('end_date', models.DateField(blank=True, db_column='End date', null=True)),
                ('stations_range', models.CharField(blank=True, db_column='Stations Range', max_length=100, null=True)),
                ('samples_range', models.CharField(blank=True, db_column='Samples Range', max_length=100, null=True)),
                ('participants', models.TextField(blank=True, db_column='Participants', null=True)),
                ('field_notebooks', models.CharField(blank=True, db_column='Field notebooks', max_length=100, null=True)),
                ('associated_project', models.CharField(blank=True, db_column='Associated project', max_length=100, null=True)),
            ],
            options={
                'db_table': 'field_missions_view',
                'managed': False,
            },
        ),
    ]
