# Generated by Django 4.0.5 on 2022-10-24 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INTERFACE', '0008_fieldmissionsview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormationsView',
        ),
    ]
