# Generated by Django 4.0.5 on 2022-10-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INTERFACE', '0012_analysisararview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisFissionTracksView',
        ),
    ]
