# Generated by Django 4.0.5 on 2022-10-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INTERFACE', '0014_analysisfissiontracksview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactsView',
        ),
    ]
