# Generated by Django 4.0.5 on 2022-10-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INTERFACE', '0016_contactsview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisUHeView',
        ),
    ]
