# Generated by Django 4.0.5 on 2022-10-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTERFACE', '0017_delete_analysisuheview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisUHeView',
            fields=[
                ('analysis_id', models.CharField(db_column='Analysis ID', max_length=100, primary_key=True, serialize=False)),
                ('material_sample_id', models.CharField(blank=True, db_column='Material Sample ID', max_length=100, null=True)),
                ('location_id', models.CharField(blank=True, db_column='Location ID', max_length=100, null=True)),
                ('decimal_latitude', models.CharField(blank=True, db_column='Decimal Latitude', max_length=100, null=True)),
                ('decimal_longitude', models.CharField(blank=True, db_column='Decimal Longitude', max_length=100, null=True)),
                ('elevation_in_meters', models.FloatField(blank=True, db_column='Elevation In Meters', null=True)),
                ('barometric_elevation_in_meters', models.FloatField(blank=True, db_column='Barometric Elevation in Meters', null=True)),
                ('verbatim_locality', models.TextField(blank=True, db_column='Verbatim Locality', null=True)),
                ('field_mission_id', models.CharField(blank=True, db_column='Field Mission ID', max_length=100, null=True)),
                ('analysed_by', models.TextField(blank=True, db_column='Analysed By', null=True)),
                ('sampling_date', models.DateField(blank=True, db_column='Sampling date', null=True)),
                ('simple_lithology_description', models.CharField(blank=True, db_column='Simple Lithology Description', max_length=100, null=True)),
                ('alteration_facies', models.CharField(blank=True, db_column='Alteration Facies', max_length=100, null=True)),
                ('metamorphism_facies', models.CharField(blank=True, db_column='Metamorphism Facies', max_length=100, null=True)),
                ('formation', models.CharField(blank=True, db_column='Formation', max_length=100, null=True)),
                ('current_storage', models.TextField(blank=True, db_column='Current storage', null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('number_4he_nccstp_g_field', models.IntegerField(blank=True, db_column='4He [nccSTP/g]', null=True)),
                ('number_238_u_ppm_field', models.FloatField(blank=True, db_column='238_U [ppm]', null=True)),
                ('number_232_th_ppm_field', models.FloatField(blank=True, db_column='232_Th [ppm]', null=True)),
                ('number_147_sm_ppm_field', models.FloatField(blank=True, db_column='147_Sm [ppm]', null=True)),
                ('eu_ppm_field', models.FloatField(blank=True, db_column='eU [ppm]', null=True)),
                ('ft', models.FloatField(blank=True, db_column='FT', null=True)),
                ('th_u', models.FloatField(blank=True, db_column='Th/U', null=True)),
                ('measured_age_ma_field', models.FloatField(blank=True, db_column='Measured age [Ma]', null=True)),
                ('number_1s_measured_age_ma_field', models.FloatField(blank=True, db_column='1s measured age  [Ma]', null=True)),
                ('corrected_age_ma_field', models.FloatField(blank=True, db_column='Corrected age  [Ma]', null=True)),
                ('number_1s_corrected_age_ma_field', models.FloatField(blank=True, db_column='1s corrected age  [Ma]', null=True)),
                ('mean_age_ma_field', models.FloatField(blank=True, db_column='Mean age  [Ma]', null=True)),
                ('number_1s_mean_age_ma_field', models.FloatField(blank=True, db_column='1s mean age  [Ma]', null=True)),
                ('location_on_gis', models.TextField(blank=True, db_column='Location on GIS', null=True)),
            ],
            options={
                'db_table': 'analysis_u_he_view',
                'managed': False,
            },
        ),
    ]
