# Generated by Django 4.0.5 on 2022-10-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTERFACE', '0019_delete_lithologydescriptionview'),
    ]

    operations = [
        migrations.CreateModel(
            name='LithologyDescriptionView',
            fields=[
                ('description_lithology_id', models.SmallIntegerField(db_column='Description Lithology ID', primary_key=True, serialize=False)),
                ('location_id', models.CharField(blank=True, db_column='Location ID', max_length=100, null=True)),
                ('simple_lithology_description', models.CharField(blank=True, db_column='Simple Lithology Description', max_length=100, null=True)),
                ('detailled_lithology_description', models.TextField(blank=True, db_column='Detailled Lithology Description', null=True)),
                ('formation', models.CharField(blank=True, db_column='Formation', max_length=100, null=True)),
                ('alteration_facies', models.CharField(blank=True, db_column='Alteration Facies', max_length=100, null=True)),
                ('metamorphism_facies', models.CharField(blank=True, db_column='Metamorphism Facies', max_length=100, null=True)),
                ('particle_type', models.CharField(blank=True, db_column='Particle Type', max_length=100, null=True)),
                ('particle_shape', models.CharField(blank=True, db_column='Particle Shape', max_length=100, null=True)),
                ('rock_texture', models.CharField(blank=True, db_column='Rock Texture', max_length=100, null=True)),
                ('color_rock_patina', models.CharField(blank=True, db_column='Color Rock Patina', max_length=100, null=True)),
                ('color_rock_into_break', models.CharField(blank=True, db_column='Color Rock Into Break', max_length=100, null=True)),
                ('fossils', models.CharField(blank=True, db_column='Fossils', max_length=100, null=True)),
                ('deformation', models.TextField(blank=True, db_column='Deformation', null=True)),
                ('minerals_assemblages', models.TextField(blank=True, db_column='Minerals Assemblages', null=True)),
                ('lithologic_description_determined_by', models.TextField(blank=True, db_column='Lithologic Description Determined By', null=True)),
                ('lithology_remarks', models.TextField(blank=True, db_column='Lithology Remarks', null=True)),
            ],
            options={
                'db_table': 'lithology_description_view',
                'managed': False,
            },
        ),
    ]
