# Generated by Django 4.0.5 on 2022-10-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTERFACE', '0021_delete_locationsview'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationsView',
            fields=[
                ('location_id', models.CharField(db_column='Location ID', max_length=100, primary_key=True, serialize=False)),
                ('decimal_longitude', models.FloatField(blank=True, db_column='Decimal Longitude', null=True)),
                ('decimal_latitude', models.FloatField(blank=True, db_column='Decimal Latitude', null=True)),
                ('geodetic_datum', models.CharField(blank=True, db_column='Geodetic datum', max_length=100, null=True)),
                ('northing_in_meters', models.DecimalField(blank=True, db_column='Northing in Meters', decimal_places=65535, max_digits=65535, null=True)),
                ('easting_in_meters', models.DecimalField(blank=True, db_column='Easting in Meters', decimal_places=65535, max_digits=65535, null=True)),
                ('georeferenced_by', models.CharField(blank=True, db_column='Georeferenced By', max_length=100, null=True)),
                ('elevation_in_meters', models.FloatField(blank=True, db_column='Elevation in Meters', null=True)),
                ('barometric_elevation_in_meters', models.FloatField(blank=True, db_column='Barometric Elevation in Meters', null=True)),
                ('georeferenced_local_date', models.DateField(blank=True, db_column='Georeferenced Local Date', null=True)),
                ('georeferenced_local_time', models.TimeField(blank=True, db_column='Georeferenced Local Time', null=True)),
                ('time_zone', models.CharField(blank=True, db_column='Time Zone', max_length=100, null=True)),
                ('verbatim_locality', models.TextField(blank=True, db_column='Verbatim Locality', null=True)),
                ('mission_detailled_name', models.TextField(blank=True, db_column='Mission Detailled Name', null=True)),
                ('observation_site_type', models.CharField(blank=True, db_column='Observation site type', max_length=100, null=True)),
                ('azimuth_of_the_osbervation', models.SmallIntegerField(blank=True, db_column='Azimuth of the osbervation', null=True)),
                ('location_remarks', models.TextField(blank=True, db_column='Location Remarks', null=True)),
                ('location_on_gis', models.TextField(blank=True, db_column='Location on GIS', null=True)),
            ],
            options={
                'db_table': 'locations_view',
                'managed': False,
            },
        ),
    ]
