# Generated by Django 4.0.5 on 2022-10-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INTERFACE', '0022_locationsview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeasurementsLinesView',
        ),
    ]
