# Generated by Django 4.0.5 on 2022-10-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INTERFACE', '0024_measurementslinesview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeasurementsPlanesView',
        ),
    ]
