# Generated by Django 4.0.5 on 2022-10-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INTERFACE', '0026_measurementsplanesview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissionsView',
        ),
    ]
