# Generated by Django 4.0.5 on 2022-10-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTERFACE', '0029_delete_samplesectionsview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleSectionsView',
            fields=[
                ('sample_section_id', models.CharField(db_column='Sample Section ID', max_length=100, primary_key=True, serialize=False)),
                ('location_id', models.CharField(blank=True, db_column='Location ID', max_length=100, null=True)),
                ('decimal_longitude', models.FloatField(blank=True, db_column='Decimal Longitude', null=True)),
                ('decimal_latitude', models.FloatField(blank=True, db_column='Decimal Latitude', null=True)),
                ('geodetic_datum', models.CharField(blank=True, db_column='Geodetic datum', max_length=100, null=True)),
                ('northing_in_meters', models.DecimalField(blank=True, db_column='Northing in Meters', decimal_places=65535, max_digits=65535, null=True)),
                ('easting_in_meters', models.DecimalField(blank=True, db_column='Easting in Meters', decimal_places=65535, max_digits=65535, null=True)),
                ('georeferenced_by', models.CharField(blank=True, db_column='Georeferenced By', max_length=100, null=True)),
                ('elevation_in_meters', models.FloatField(blank=True, db_column='Elevation in Meters', null=True)),
                ('barometric_elevation_in_meters', models.FloatField(blank=True, db_column='Barometric Elevation in Meters', null=True)),
                ('georeferenced_local_date', models.DateField(blank=True, db_column='Georeferenced Local Date', null=True)),
                ('georeferenced_local_time', models.TimeField(blank=True, db_column='Georeferenced Local Time', null=True)),
                ('time_zone', models.CharField(blank=True, db_column='Time Zone', max_length=100, null=True)),
                ('verbatim_locality', models.TextField(blank=True, db_column='Verbatim Locality', null=True)),
                ('mission_detailled_name', models.TextField(blank=True, db_column='Mission Detailled Name', null=True)),
                ('simple_lithology_description', models.CharField(blank=True, db_column='Simple Lithology Description', max_length=100, null=True)),
                ('detailled_lithology_description', models.TextField(blank=True, db_column='Detailled Lithology Description', null=True)),
                ('thin_sec_orientation', models.CharField(blank=True, db_column='Thin sec. orientation', max_length=100, null=True)),
                ('plane_type', models.CharField(blank=True, db_column='Plane type', max_length=100, null=True)),
                ('plane_orientation', models.TextField(blank=True, db_column='Plane Orientation', null=True)),
                ('line_type', models.CharField(blank=True, db_column='Line Type', max_length=100, null=True)),
                ('line_orientation', models.TextField(blank=True, db_column='Line orientation', null=True)),
                ('number_of_sections', models.SmallIntegerField(blank=True, db_column='Number of sections', null=True)),
                ('position_on_gis', models.TextField(blank=True, db_column='Position on GIS', null=True)),
            ],
            options={
                'db_table': 'sample_sections_view',
                'managed': False,
            },
        ),
    ]
