# Generated by Django 4.0.5 on 2022-10-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTERFACE', '0031_delete_samplesview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplesView',
            fields=[
                ('material_sample_id', models.CharField(db_column='Material Sample ID', max_length=100, primary_key=True, serialize=False)),
                ('location_id', models.CharField(blank=True, db_column='Location ID', max_length=100, null=True)),
                ('decimal_longitude', models.FloatField(blank=True, db_column='Decimal Longitude', null=True)),
                ('decimal_latitude', models.FloatField(blank=True, db_column='Decimal Latitude', null=True)),
                ('geodetic_datum', models.CharField(blank=True, db_column='Geodetic datum', max_length=100, null=True)),
                ('northing_in_meters', models.DecimalField(blank=True, db_column='Northing in Meters', decimal_places=65535, max_digits=65535, null=True)),
                ('easting_in_meters', models.DecimalField(blank=True, db_column='Easting in Meters', decimal_places=65535, max_digits=65535, null=True)),
                ('georeferenced_by', models.CharField(blank=True, db_column='Georeferenced By', max_length=100, null=True)),
                ('elevation_in_meters', models.FloatField(blank=True, db_column='Elevation in Meters', null=True)),
                ('barometric_elevation_in_meters', models.FloatField(blank=True, db_column='Barometric Elevation in Meters', null=True)),
                ('georeferenced_local_date', models.DateField(blank=True, db_column='Georeferenced Local Date', null=True)),
                ('georeferenced_local_time', models.TimeField(blank=True, db_column='Georeferenced Local Time', null=True)),
                ('time_zone', models.CharField(blank=True, db_column='Time Zone', max_length=100, null=True)),
                ('verbatim_locality', models.TextField(blank=True, db_column='Verbatim Locality', null=True)),
                ('mission_detailled_name', models.TextField(blank=True, db_column='Mission detailled name', null=True)),
                ('sampling_date', models.DateField(blank=True, db_column='Sampling Date', null=True)),
                ('sample_type', models.CharField(blank=True, db_column='Sample type', max_length=100, null=True)),
                ('first_sample_aim', models.CharField(blank=True, db_column='First Sample Aim', max_length=100, null=True)),
                ('second_sample_aim', models.CharField(blank=True, db_column='Second Sample Aim', max_length=100, null=True)),
                ('lithology_description', models.CharField(blank=True, db_column='Lithology Description', max_length=100, null=True)),
                ('alteration_facies', models.CharField(blank=True, db_column='Alteration Facies', max_length=100, null=True)),
                ('metamorphism_facies', models.CharField(blank=True, db_column='Metamorphism Facies', max_length=100, null=True)),
                ('formation', models.CharField(blank=True, db_column='Formation', max_length=100, null=True)),
                ('plane_type', models.CharField(blank=True, db_column='Plane type', max_length=100, null=True)),
                ('plane_orientation', models.TextField(blank=True, db_column='Plane Orientation', null=True)),
                ('line_type', models.CharField(blank=True, db_column='Line type', max_length=100, null=True)),
                ('line_orientation', models.TextField(blank=True, db_column='Line Orientation', null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('current_storage', models.TextField(blank=True, db_column='Current storage', null=True)),
                ('location_on_gis', models.TextField(blank=True, db_column='Location on GIS', null=True)),
            ],
            options={
                'db_table': 'samples_view',
                'managed': False,
            },
        ),
    ]
